### ISSUE TITLE
vm-compute-0 can't contact apiserver

### ISSUE THREAD

**Issue by jim-minter** [jim-minter/azure-helm#34]
reproducer: run `oc new-app nginx`, deploy pod fails unable to contact apiserver.  On the node, `curl https://172.31.0.1` hangs.  Doesn't seem to happen on vm-infra-0.

**Comment by jim-minter** [comment]
The tunnel connection is currently quieter on vm-compute-0 because it doesn't handle cluster traffic (yet).  I think the issue is that some gateway between client and server is forgetting the connection and a TCP reset either isn't sent or gets lost.  I'm suspicious of Azure LB, especially since Kubernetes enables "Floating IP (direct server return)".

fbc66015886e314ce7b7920f19d6dd659767f74f adds a 10 second TCP timeout on each end of the connection and I haven't seen the problem since that.  However this needs to be reworked to an application-level heartbeat.

**Comment by jim-minter** [comment]
A diagnostic is that when this happens, `netstat` on the client reports the Send-Q associated with the connection as being non-zero and `tcpdump` shows repeated unacknowledged attempts to send data to the server.

**Comment by pweil-** [comment]
TCP resets not being sent were an issue with the cloud provider as well. :(

**Comment by jim-minter** [comment]
app level heartbeat was added.
