### ISSUE TITLE
Prioritize sdn creation in addon sync

### ISSUE THREAD

**Issue by kargakis** [jim-minter/azure-helm#44]
We will be able to squeeze more time out of cluster bootstrap if we optimize addon creation (create SDN before any other pod so nodes can turn ready asap and new pods get scheduled as soon as they get created. 

@jim-minter @pweil- @mjudeikis

**Comment by jim-minter** [comment]
The addon creation process tends to complete before the nodes have even booted.  Does the kubelet order pod creations by creationTimestamp or something?  I think the difficulty is more around the size of the container images we ship.

**Comment by kargakis** [comment]
> The addon creation process tends to complete before the nodes have even booted. Does the kubelet order pod creations by creationTimestamp or something? I think the difficulty is more around the size of the container images we ship.

Hrm, I think you are right. The fact that we don't see the sdn pods created asap is because daemon set pods get created when nodes first register in the cluster.

**Comment by pweil-** [comment]
Pod priority classes will only help with scheduling.  Higher priority classes will be scheduled first if the can be.  If the issue is unready nodes or long docker pulls I don't think there is much that can be done other than pre-population of images.

**Comment by kargakis** [comment]
ack

closing in favor of https://trello.com/c/gqaNTmqj/155-images-low-priority-consider-prebaking-docker-images-into-golden-images
