### ISSUE TITLE
Figure out how to regenerate config for individual components

### ISSUE THREAD

**Issue by kargakis** [jim-minter/azure-helm#48]
We should be able to regenerate config for individual components while retaining the rest of the config.

eg. I want to regenerate only the SC certificates, or the docker registry config, or ....

@jim-minter @pweil- @mjudeikis @kwoodson

**Comment by jim-minter** [comment]
The way I'd thought of doing this was by only generating dynamic config values (e.g. certs) if they don't exist.  That way regeneration of a value (e.g. cert rotation) would be triggerable by deleting the old value.

I'd supposed that in the upgrade code, we'd have a pre-hook before running generate which would have the capability to delete config values that needed to be regenerated for whatever reason.
